#!/bin/bash

set -e

root_dir="$(cd "$(dirname "$0")" && pwd)"
llvm_dir="$root_dir/llvm-passes"
build_dir="$llvm_dir/build"
include_dir="$llvm_dir/include"
output_dir="$llvm_dir/output"
scripts_dir="$llvm_dir/scripts"
src_dir="$llvm_dir/src"
test_dir="$llvm_dir/test"

mkdir -p "$build_dir" "$output_dir"

echo "Executing Scripts"
python3 "$scripts_dir/LibcCallNames.py"
python3 "$scripts_dir/DummySyscalls.py"
echo "Done"
echo -en "\n"
echo "Compiling Test Program"
clang -emit-llvm -c "$test_dir/test.c" -o "$test_dir/test.bc"
echo "Done"
echo -en "\n"
echo "Compiling Pass 1/3"
clang++ -std=c++17 -shared -fPIC $(llvm-config --cxxflags --ldflags --libs --system-libs) "$src_dir/LibcPass.cpp" -o "$build_dir/LibcPass.so"
echo "Done"
echo -en "\n"
echo "Compiling Pass 2/3"
clang++ -std=c++17 -shared -fPIC $(llvm-config --cxxflags --ldflags --libs --system-libs) "$src_dir/InstrumentPass.cpp" -o "$build_dir/InstrumentPass.so"
echo "Done"
echo -en "\n"
echo "Compiling Pass 3/3"
clang++ -std=c++17 -shared -fPIC $(llvm-config --cxxflags --ldflags --libs --system-libs) "$src_dir/SyscallPass.cpp" -o "$build_dir/SyscallPass.so"
echo "Done"
echo -en "\n"
echo "Running Libc Call Graph Pass"
opt -load-pass-plugin="$build_dir/LibcPass.so" -passes=libc-cfg-pass -debug-pass-manager "$test_dir/test.bc" -o /dev/null
echo "Done"
echo -en "\n"
mv "$root_dir/test_cfg.dot" "$output_dir/test_cfg.dot"
echo "Running Instrumentation + Syscall Graph Pass"
opt -load-pass-plugin="$build_dir/InstrumentPass.so" -load-pass-plugin="$build_dir/SyscallPass.so" -passes="instrument-pass,syscall-cfg-pass" -debug-pass-manager "$test_dir/test.bc" -o /dev/null
echo "Done"
echo -en "\n"
mv "$root_dir/test_cfg.dot" "$output_dir/test_cfg_mod.dot"
echo "Generating PNG Files"
cd "$output_dir"
dot -Tpng test_cfg.dot -o LibcCFG.png
dot -Tpng test_cfg_mod.dot -o SyscallCFG.png
cd "$root_dir"
echo "Done"
echo -en "\n"
echo "Cleaning Up"
rm "$test_dir/test.bc"
rm "$include_dir/CallNames.h"
rm "$include_dir/DummySyscalls.h"
rm "$output_dir/test_cfg.dot"
rm "$output_dir/test_cfg_mod.dot"
rm "$build_dir/LibcPass.so"
rm "$build_dir/InstrumentPass.so"
rm "$build_dir/SyscallPass.so"
rm -rf "$build_dir"
echo "Done"

